config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks, except: [:show, :update, :edit]
  resources :categories
  resources :articles
  resources :users, only: [:index, :show]
  devise_for :users
  resources :votes, only: [:create, :new, :destroy, :new]
  root to: "categories#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_one_attached :image
  has_and_belongs_to_many :categories, class_name: 'Category'
  has_many :votes
  has_many :bookmarks
  validates :categories_list, presence: true
  validates :image, presence: true
  validates :title, length: { minimum: 10 }
  validates :text, length: { minimum: 15 }

  def categories_list
    categories
  end

  def categories_list=(arr_ids)
    arr_ids.each do |n|
      categories << Category.find(n.to_i)
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def new
    @categories = Category.all
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  def show; end

  # POST /articles
  def create
    @categories = Category.all
    @article = current_user.articles.new(article_params)
    unless @article.image.attached?
      @article.image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'default.jpg')),
                            filename: 'default.jpg',
                            content_type: 'image/jpg')
    end

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /articles/1
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :text, :image, categories_list: [])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="form-wrapper">
  <%= form_with(model: article, local: true) do |form| %>
    <% if article.errors.any? %>
      <div id="error_explanation">
        <p><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</p>

        <ul>
          <% article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :image %><br>
      <%= form.file_field :image, direct_upload: true %>
    </div>
    
    <div class="field">
      <%= form.label "Categories" %><br>
      <% @categories.each do |c| %>
        <span class="mr-2">
          <%= form.check_box("categories_list", {:multiple => true}, c.id, nil) %>
          <label><%= h c.name -%></label>
        </span>
      <% end %>
    </div>

    <p><%= link_to "CREATE NEW CATEGORY", new_category_path, :class => "pr-2 navbar-links", target: :_blank %> </p>


    <div class="field">
      <%= form.label :text %><br>
      <%= form.text_area(:text, cols: 60, rows: 9) %>
    </div>

    <div class="actions mb-5">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<h2>Editing Article</h2>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= article.author_id %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h2>New Article</h2>

<%= render 'form', article: @article %>

<p class = "text-center" >
    <%= link_to '<< Back', articles_path %>
</p>

app/views/articles/show.html.erb
<h2>
  <%= @article.title %>
</h2>
<div>
    <%= image_tag(@article.image, height: '280', width: '580', class: 'mx-auto d-block') %>
</div>
<p class="mx-auto mt-4 text-show text-justify">
  <%= @article.text %>
</p>
<p class="mx-auto mt-4 text-show text-justify">
  <%= link_to 'Back', categories_path %>
</p>