config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks, except: [:show, :update, :edit]
  resources :categories
  resources :articles
  resources :users, only: [:index, :show]
  devise_for :users
  resources :votes, only: [:create, :new, :destroy, :new]
  root to: "categories#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :articles, class_name: 'Article'
  validates :name, presence: true
  validates :priority, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories
  def index
    @categories = Category.all.order(priority: :desc).includes(:articles)
    id = Article.all.joins(:votes).group(:id).count.max_by { |_k, v| v }
    @most_voted = if id.nil?
                    nil
                  else
                    Article.find(id[0])
                  end
  end

  # GET /categories/1
  def show
    @category = Category.find(params[:id])
    @articles = Category.find(params[:id]).articles.includes(:votes).order(created_at: :desc).joins(:image_attachment)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to new_article_path, notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /categories/1
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def last_article_image(cat)
    a = article_last(cat)
    if a.nil?
      image_url('default.jpg')
    else
      url_for(a.image)
    end
  end

  def last_article_title(cat)
    a = article_last(cat)
    if a.nil?
      "Write the first Article for #{cat.name
			                                } Category"
    else
      a.title
    end
  end

  def article_last(cat)
    cat.articles.last
  end

  def most_voted_partial
    if !@most_voted.nil?
      (render 'main_article', most_voted: @most_voted).html_safe
    else
      (render partial: 'main_default').html_safe
    end
  end

  def order(index)
    if (index % 4) >= 2
      'order-1'
    else
      'order-2'
    end
  end
end

app/views/categories/_form.html.erb
<div class="form-wrapper">
  <%= form_with(model: category, local: true) do |form| %>
    <% if category.errors.any? %>
      <div id="error_explanation">
        <p><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</p>

        <ul>
          <% category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %></br>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :priority %></br>
      <%= form.number_field :priority %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<main class="container-fluid p-0">
	<div class="row">
		<%= most_voted_partial %>
		<% @categories.each do |c| %>
			<div class= "col-3 p-0 category-image" style="background-image: url(<%= last_article_image(c) %>)">
				<div class="cover-img d-flex flex-column justify-content-between">
					<div>
						<%= link_to "#{c.name}", category_path(c), :class => "text-uppercase article-title header-effect"%>
						<span class= "effect"></span>
					</div>
					<p class= "text-right article-title text-white" ><%= last_article_title(c) %></p>
				</div>
			</div>
		<% end %>
		</div>
	</div>
</main>

app/views/categories/new.html.erb
<h2>New Category</h2>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<div class="row">
	<% @articles.each_with_index do |article, i| %>
	  <div class = "col-6 row p-0">
	    <div class="col-6 image-square order-2 p-0" style="background-image: url(<%= url_for(article.image) %>)">
	    	<div class="cover-img p-0">
	    	</div>
	    </div>
	    <div class ="d-flex flex-column col-6 text-square <%= order(i) %> px-3 pb-3 pt-1 justify-content-between">
	    	<div class="article-text">
		    	<%= link_to "#{@category.name}", category_path(@category), :class => "text-uppercase text_orange header-effect category-name"%>
		    	<span class= "effect-orange mb-3
		    	"></span>
		    	<p class="article-title-show"><%= article.title %></p>
				<p><%= truncate("#{article.text}", :length => 120) %></p>

	    	</div>
			<div>
				<p class="text-right"><strong> <%= article.author.username %></strong></p>
				<p class="text-right">
					<span class="mr-2"><%= vote_button(article) %></span>
					<%= bookmark_button(article) %>
	    		</p>
	    	</div>

		</div>
	  </div>
	<% end %>
</div>