config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks, except: [:show, :update, :edit]
  resources :categories
  resources :articles
  resources :users, only: [:index, :show]
  devise_for :users
  resources :votes, only: [:create, :new, :destroy, :new]
  root to: "categories#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Render Customized Navbar for authenticated
  def load_nav
    if !current_user.nil?
      (render partial: 'user_nav').html_safe
    else
      (render partial: 'login_nav').html_safe
    end
  end

  def notice_display
    content_tag(:p, notice, class: 'alert alert-dark text-center').html_safe if notice
  end

  def alert_display
    content_tag(:p, alert, class: 'alert alert-dark text-center').html_safe if alert
  end
end

app/views/application/_login_nav.html.erb
<div class="right">
    <%= link_to "LOGIN", new_user_session_path, :class =>  "pr-2 navbar-links" %> |
    <%= link_to "REGISTER", new_user_registration_path, :class => "pr-2 navbar-links" %> 
</div>

app/views/application/_main_article.html.erb
<article class="first-row main-article col-12 p-0" style="background-image: url(<%= (url_for(most_voted.image)) %>)">
    <div class="cover-gradient p-4 d-flex flex-column justify-content-end">
        <p class="main-title text_orange text-right text-uppercase"> <%= @most_voted.title %> </p> 
        <p class = "article_text text-right text-white"> <%= truncate("#{@most_voted.text}", :length => 135) %> </p>
    </div>
</article>

app/views/application/_main_default.html.erb
<article class="first-row main-article col-12 p-0" style="background-image: url(<%= image_url('default.jpg') %>)">
    <div class="cover-gradient p-4 d-flex flex-column justify-content-end">
        <p class="main-title text_orange text-right text-uppercase"> Write an Article </p> 
        <p class = "article_text text-right text-white"> "Do you wanna publish amazing articles on our magazine? Please create a new article" </p>
    </div>
</article>

app/views/application/_user_nav.html.erb
<ul class="middle d-flex align-items-center ">
    <li><%= link_to "HOME", categories_path, :class => "text_orange pr-2" %></li>
    <li><%= link_to "CREATE ARTICLE", new_article_path, :class => "pr-2 navbar-links" %></li>
    <li><%= link_to "BOOKMARKS", bookmarks_path, :class => "pr-2 navbar-links" %></li>
</ul>
<div class="right">
	<span>You are Logged In, <%= current_user.username%></span> |
    <%= link_to "SIGN OUT", destroy_user_session_path, method: :delete, :class => "navbar-links" %>
</div>